#!/usr/bin/env bash
# Bash script that install NGINX on a server and configures it.

apt-get update -y && apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
