#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Bash script that displays To infinity and beyond indefinitely.
# And prints 'I hate the kill command' when receiving a SIGTERM signal.
# And prints 'Y U no love me?!' when receiving a SIGINT signal.
# Deletes the file /var/run/myscript.pid and terminates itself when receiving:
# a SIGQUIT or SIGTERM signal.

function terminate {
	rm -r /var/run/myscript.pid
	exit 0
}

echo $$ > /var/run/myscript.pid

while (true)
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command && terminate"' 15
	trap terminate 3
	trap 'echo "Y U no love me?!"' 2
done
