#!/usr/bin/env bash
# This script is used to run the command whoami as another user.
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s/listen 80/listen 8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
